### ISSUE TITLE
Map Mate Ver. 0.10 Works on English Version !!

### ISSUE THREAD

**Issue by rods321** [Toukibi/ToSAddon#1]
This addon Map Mate is working on English version of TOS. Really great addon ! Just need a translation to be perfect.

**Comment by Toukibi** [comment]
Thank you for reporting the operation in the IToS version.
For check IToS version, I have to install IToS to my computer.(Honestly, I cannot install IToS in the usual way in Japan.)
And I have to deal with the replacement of resources like ShopHelper.
So I am glad if you wait a while for my localization work.

**Comment by Toukibi** [comment]
Today, I uploaded update of Map Mate Ver. 0.15.
By this update, we can switch to the English display mode.
To switch to the English display mode, please use the command **`/mmate en`**
