### ISSUE TITLE
[MapMate] Monster List became a separate window instead of popup

### ISSUE THREAD

**Issue by hiiwave** [Toukibi/ToSAddon#12]
Thank you very much for this awesome addon, and it really makes our life easier!
Only that recently I found a small issue, as the monster list became a separate window rather than a popup.

![screenshot_20170814_00001](https://user-images.githubusercontent.com/5608511/29277764-372a1854-8145-11e7-99e3-acc9855fe65f.jpg)

When I press the right button on this separate window, it gives me
![screenshot_20170814_00002](https://user-images.githubusercontent.com/5608511/29277782-4a77643e-8145-11e7-83a6-470018550aab.jpg)

And when I move my mouse onto the monster icon, nothing happened.

Do you know any possible reason for that? Thank you so much.

**Comment by Toukibi** [comment]
I'm sorry for the late reply. I confirmed the problem today.

It is not yet in JToS, but it seems that the screen design has changed in IToS.
As a result of this influence, there seems to be a malfunction in display design with multiple addons including MapMate.

Originally, the close button should be displayed in the upper right of the monster list. However, with the design change, the image of the close button is deleted, it seems that nothing is displayed.

Although it is not displayed, you can close the monster list by clicking on the top right of the monster list. Can I respond with it until the correction is over?

**Comment by hiiwave** [comment]
Thanks for the response! I'm out of home and will try clicking the hidden button once I'm back on Sunday, thank you!

**Comment by hiiwave** [comment]
I've confirmed this solution works. Thanks!
