### ISSUE TITLE
[ShopHelper] 'Increase Magic Defense' support

### ISSUE THREAD

**Issue by holysnipz** [Toukibi/ToSAddon#14]
~~Sorry, i'm too lazy to edit your code and made PR.~~
~~here's little information:~~

~~- BuffID: 260~~
~~- [SkillID: 40808](https://tos.neet.tv/skills/40808)~~
~~- MaxLevel: 15~~
~~- Skill tooltip said that it Using 1x Holy Water (so the shop should be 10x), the cost should be same as [Aspersion](https://tos-jp.neet.tv/skills/40201)~~
~~- not sure about average price~~

**Comment by Toukibi** [comment]
Hello. Thank you for writing.
Well, as for the subject matter, I just checked that ShopHelper does not work properly. Besides buff items, there are also more portal shops.

Currently, I am finishing the measures, investigating the price and checking the operation. So it is a pleasure to have you wait for a while.

**Comment by holysnipz** [comment]
> Currently, I am finishing the measures, investigating the price and checking the operation. So it is a pleasure to have you wait for a while.

That's nice progress to heard, thanks.

btw, right now i have no problem for wait, 'cause i've already made a quick edit to skip Increase Magic Defense on buff shop 😉

**Comment by Toukibi** [comment]
I released the updated version of Shop Helper a while ago.

After all, I set the default average value same as the price of Aspersion.
I'm doing only the minimal modification, but I hope you can try it.
