### ISSUE TITLE
Tooltip Helper in iToS

### ISSUE THREAD

**Issue by zadezl** [Toukibi/ToSAddon#17]
Hi Toukibi, your newest release of Tooltip Helper doesnt show drop ratio anymore.
I hope you could spend some time to check it
Thank you very much for all those great add-ons
![1695fd36394487e39b41910619a897d847cd44d1_1_413x500](https://user-images.githubusercontent.com/36026174/35665442-cb56369a-0758-11e8-8130-6a223509c456.png)

![6b86e0998f20964dbd9bffef5656f7935f8ebf9d](https://user-images.githubusercontent.com/36026174/35665355-81895ad8-0758-11e8-98dc-92bd5ef7045b.png)

**Comment by Toukibi** [comment]
Thank you for the report.

Today, I checked the situation with IToS.  
My mistake is caused. Please wait for a while because I'm preparing for publication after confirming what I've corrected.

**Comment by Toukibi** [comment]
Today I released Tooltip Helper ver 1.04 which corrected this problem.
I am pleased if you can check it.

**Comment by zadezl** [comment]
Thank you so much, its working perfectly now :D
