### ISSUE TITLE
Hi could you make this addon work again ?

### ISSUE THREAD

**Issue by rods321** [Toukibi/ToSAddon#2]
This addon is Itemdrops used to work before. This addon show items dropped on ground and alert you in chat as system message. If possible to help me thanks.

http://www.filedropper.com/itemdrops--v100

**Comment by Toukibi** [comment]
I also used ItemDrops in the past. However, with the official response, the pillars of light appeared in the item. And I had no idea how far it was from the behavior of ItemDrops and where it was official behavior.
So, if you do not mind, could you tell me about the behavior of ItemDrops that wants to be revived in particular?

**Comment by rods321** [comment]
When you put in chat /drops you can see this menu http://prntscr.com/eoo6e9 ... This command /drops msg used to allert in chat system when a item common drop on ground. And you could make allert you about rarity of items changing common, rare, epic, legendary. But not anymore addon did stop to show that message on chat when item drop.

If you have skype or discord to talk better would help !

**Comment by Toukibi** [comment]
It seems that the function name on the item rank has been changed in this previous update. Therefore, it seems that there is a problem.
However, in Japan, that update has to wait until February 29th. So I will investigate after that day.

**Comment by rods321** [comment]
Thanks ! If you have any other idea to that addon make a similar one or a better. Maybe that would be easier than fix that old one.

**Comment by holysnipz** [comment]
@rods321 about the message doesn't work. 
just unpack the `.ipf` and change `GetModifiedProperiesString` to `GetModifiedPropertiesString` (there should be only 1 function) in `itemdrops.lua`
Then save, repack, copy to game directory (don't forget to include unicode char too)

and that's all of it

**Comment by Toukibi** [comment]
Sorry for being late.
This problem occurred because function name changed as @holysnipz said. So, we can recover by modifying it.
I created an .ipf package that fixed this problem. You can download it from the URL below.

https://github.com/Toukibi/ToSAddon/tree/master/Do-It-Yourself/With_ipf

**Comment by rods321** [comment]
Thanks
