### ISSUE TITLE
MapMate Clock

### ISSUE THREAD

**Issue by okmoon** [Toukibi/ToSAddon#6]
Can you show second by adding to the clock?

**Comment by Toukibi** [comment]
Hello. You say you want to display seconds on the clock, but first of all we can not display the seconds of server time. Although it is not impossible in principle, communication must be performed at least twice per second to the server, and if it is heavily used, it may be a load on the server.  
  
It is not impossible if it is a local time display. However, according to the current MapMate specification, MapMate can only acquire the time event once a minute.  

So I would like to know if there is a use just to implement that specification. If you do not mind, could you tell me what you would like to do with the seconds display?

**Comment by okmoon** [comment]
First of all thank you for your detailed reply.
I had to get a monster every minute to get the quest item. (2nd Demon Prison for The Collection)
I did not know the exact time with the displayed clock.
So I used the TimePlus addon together.

**Comment by okmoon** [comment]
I checked a new version.
I really appreciate the implementation of what I said.
I think ToS Life will be more fun thanks to you. ;)
