### ISSUE TITLE
[Question] Can we have a config for 'Hide other players' in ShopHelper?

### ISSUE THREAD

**Issue by holysnipz** [Toukibi/ToSAddon#7]
I'm a `mouse-mode` user and find this pretty annoyed in some situations with my `ALT + <keys>` skill hotkeys. Any kind of config is fine _(for me)_.

I know i can do that myself, but just asking for the future release. 
Too lazy to edit when updating 😂

**Comment by Toukibi** [comment]
Hello. And I'm sorry not respond for a long time.

Today, I updated ShopHelper to Ver.0.82.
This update implements the config for hide other players.

Actually, I'm also `mouse-mode` user. But I usually use `Ctrl + <keys>` for hotkeys to use skills and open windows. So I used the Alt key.
Probably, it would be perfect if I could implement Key Config, but I don't have the skill to implement it. So, this time I implemented only on and off setting.

**Comment by holysnipz** [comment]
With simple toggle `Hold ALT Key to hide other players` implemented since `ShopHelper v0.8.2`
Mark this topic as closed for now.

Thanks for the update anyway.

_ps. two months late, cause i'm too lazy to sign-in after reinstall Windows_ lol
